import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import pool from './db.js';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Initialize database schema (add auto-increment if missing)
const initDb = async () => {
  try {
    // Customer ID auto-increment
    const resCust = await pool.query(`
      SELECT is_identity 
      FROM information_schema.columns 
      WHERE table_name = 'customer' AND column_name = 'customer_id'
    `);
    
    if (resCust.rows[0]?.is_identity === 'NO') {
      const maxIdRes = await pool.query('SELECT COALESCE(MAX(customer_id), 0) as max_id FROM customer');
      const startId = parseInt(maxIdRes.rows[0].max_id) + 1;
      await pool.query(`ALTER TABLE customer ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH ${startId})`);
      console.log('customer_id is now auto-incrementing.');
    }

    // ATR ID auto-increment
    const resAtr = await pool.query(`
      SELECT is_identity 
      FROM information_schema.columns 
      WHERE table_name = 'atr' AND column_name = 'atr_id'
    `);

    if (resAtr.rows[0]?.is_identity === 'NO') {
      const maxIdRes = await pool.query('SELECT COALESCE(MAX(atr_id), 0) as max_id FROM atr');
      const startId = parseInt(maxIdRes.rows[0].max_id) + 1;
      await pool.query(`ALTER TABLE atr ALTER COLUMN atr_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH ${startId})`);
      console.log('atr_id is now auto-incrementing.');
    }
  } catch (err) {
    console.error('Error initializing DB:', err.message);
  }
};

// Seed database with required data for ATR
const seedDb = async () => {
  try {
    // Check if Company exists
    const compRes = await pool.query('SELECT count(*) FROM company');
    if (compRes.rows[0].count == 0) {
      await pool.query("INSERT INTO company (comp_id, comp_name, comp_address, comp_phoneno) VALUES (1, 'SC Courier Services', 'No 1, Logistics Way, Colombo', '0112345678')");
    }

    // Check if Departments exist
    const depRes = await pool.query('SELECT count(*) FROM department');
    if (depRes.rows[0].count == 0) {
      const departments = [
        [1, 'Operations', 1], [2, 'Finance', 1], [3, 'Human Resources', 1],
        [4, 'Logistics', 1], [5, 'Administration', 1], [6, 'IT', 1], [7, 'Marketing', 1]
      ];
      for (const dep of departments) {
        await pool.query('INSERT INTO department (dep_id, dep_name, comp_id) VALUES ($1, $2, $3)', dep);
      }
    }

    // Check if Branch exists
    const branchRes = await pool.query('SELECT count(*) FROM branch');
    if (branchRes.rows[0].count == 0) {
      await pool.query("INSERT INTO branch (branch_id, branch_location) VALUES (101, 'Colombo Main Branch')");
    }

    // Check if Staff exist
    const staffRes = await pool.query('SELECT count(*) FROM staff');
    if (staffRes.rows[0].count == 0) {
      const staff = [
        [801, 'Mr. Perera', '0771234567', 101, 'Director', 'Active'],
        [802, 'Mrs. Silva', '0772345678', 101, 'GM', 'Active'],
        [803, 'Mr. Wijesinghe', '0773456789', 101, 'AGM', 'Active'],
        [804, 'Mrs. Jayawardena', '0774567890', 101, 'HOD', 'Active'],
        [805, 'Mr. Ratnayake', '0775678901', 101, 'Manager', 'Active']
      ];
      for (const s of staff) {
        await pool.query('INSERT INTO staff (staff_id, staff_name, staff_phone, branch_id, staff_role, staff_active_status) VALUES ($1, $2, $3, $4, $5, $6)', s);
      }
    }
    console.log('Database seeded successfully.');
  } catch (err) {
    console.error('Error seeding DB:', err.message);
  }
};

(async () => {
  await initDb();
  await seedDb();
})();

// Register customer
app.post('/api/register', async (req, res) => {
  const { name, email, address, phone, password } = req.body;
  try {
    const result = await pool.query(
      'INSERT INTO customer (cust_name, cust_email, cust_address, cust_phoneno, cust_password, cust_type) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *',
      [name, email, address, phone, password, 'Individual']
    );
    res.json({ success: true, user: result.rows[0] });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Registration failed', error: err.message });
  }
});

// Login customer
app.post('/api/login', async (req, res) => {
  const { email, password } = req.body;
  try {
    const result = await pool.query(
      'SELECT * FROM customer WHERE cust_email = $1 AND cust_password = $2',
      [email, password]
    );
    if (result.rows.length > 0) {
      res.json({ success: true, user: result.rows[0] });
    } else {
      res.status(401).json({ success: false, message: 'Invalid email or password' });
    }
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Login failed', error: err.message });
  }
});

// ATR submission
app.post('/api/atr', async (req, res) => {
  const {
    atrNumber, department, requiredDate, requiredTime, vehicleType,
    purposeOfTravel, passengerName, passengerDesignation,
    estimatedDistance, estimatedCost, actualDistance, actualCost,
    status, approvedBy, approvalDate
  } = req.body;

  try {
    const result = await pool.query(`
      INSERT INTO atr (
        dep_id, atr_number, required_date, required_time, vehicle_type,
        purpose_of_travel, principal_passenger_name, principal_passenger_designation,
        estimated_distance, estimated_cost, actual_distance, actual_cost,
        status, approved_by, approval_date
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
      RETURNING *
    `, [
      department, atrNumber, requiredDate || null, requiredTime || null, vehicleType,
      purposeOfTravel, passengerName, passengerDesignation,
      estimatedDistance || 0, estimatedCost || 0, actualDistance || 0, actualCost || 0,
      status || 'Pending', approvedBy || null, approvalDate || null
    ]);
    res.json({ success: true, atr: result.rows[0] });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'ATR submission failed', error: err.message });
  }
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
